#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jan 28 11:46:45 2022

@author: thkam
"""

import numpy as np
from defaults import constants

designs = {
  'A' :  {
    'room_L' : 5,
    'room_W' : 5,
    'room_H' : 3,
    'refl_north' : 0.8,
    'refl_south' : 0.8,
    'refl_east' : 0.8,
    'refl_west' : 0.8,
    'refl_ceiling' : 0.8,
    'refl_floor' : 0.3,
    'm_sensor' : 1,
    'r_sensor' : np.array([2.5, 2.5, 0]),
    'm_master' : 1,
    'r_master' : np.array([2.5, 2.5, 3]),
    'FOV_master' : np.pi / 2.0,
    'FOV_sensor' : np.pi / 2.0,
    'amb_L1' : 1.0,
    'amb_L2' : 1.0,
    'nR_sensor' : constants.ez,
    'nS_sensor' : constants.ez,
    'nR_master' : -constants.ez,
    'nS_master' : -constants.ez,
    'no_bounces' : 4,
    'Rb_master' : 10e3,
    'Rb_sensor' : 10e3,  
    'PT_sensor' : 25e-3,
    'PT_master' : 6,
    'A_master' : 1e-4,
    'A_sensor' : 1e-4
    },
  'Β1' :  {
    'room_L' : 7.5,
    'room_W' : 5,
    'room_H' : 3,
    'refl_north' : 0.3,
    'refl_south' : 0.56,
    'refl_east' : 0.3,
    'refl_west' : 0.12,
    'refl_ceiling' : 0.69,
    'refl_floor' : 0.09,
    'm_sensor' : 1,
    'r_sensor' : np.array([2.5, 2.5, 0]),
    'm_master' : 1,
    'r_master' : np.array([2.5, 2.5, 3]),
    'FOV_master' : np.pi / 2.0,
    'FOV_sensor' : np.pi / 2.0,
    'amb_L1' : 1.0,
    'amb_L2' : 1.0,
    'nR_sensor' : constants.ez,
    'nS_sensor' : constants.ez,
    'nR_master' : -constants.ez,
    'nS_master' : -constants.ez,
    'no_bounces' : 4,
    'Rb_master' : 10e3,
    'Rb_sensor' : 10e3,  
    'PT_sensor' : 25e-3,
    'PT_master' : 6,
    'A_master' : 1e-4,
    'A_sensor' : 1e-4     
    },
    'B' :  {
    'room_L' : 10,
    'room_W' : 10,
    'room_H' : 4,
    'refl_north' : 0.3,
    'refl_south' : 0.56,
    'refl_east' : 0.3,
    'refl_west' : 0.12,
    'refl_ceiling' : 0.69,
    'refl_floor' : 0.09,
    'm_sensor' : 1,
    'r_sensor' : np.array([2.5, 2.5, 0]),
    'm_master' : 1,
    'r_master' : np.array([5, 5, 4]),
    'FOV_master' : np.pi / 2.0,
    'FOV_sensor' : np.pi / 2.0,
    'amb_L1' : 2.0,
    'amb_L2' : 2.0,
    'nR_sensor' : constants.ez,
    'nS_sensor' : constants.ez,
    'nR_master' : -constants.ez,
    'nS_master' : -constants.ez,
    'no_bounces' : 4,
    'Rb_master' : 10e3,
    'Rb_sensor' : 10e3,  
    'PT_sensor' : 25e-3,
    'PT_master' : 6,
    'A_master' : 1e-4,
    'A_sensor' : 1e-4
   },
   'C' :  {
    'room_L' : 10,
    'room_W' : 10,
    'room_H' : 4,
    'refl_north' : 0.8,
    'refl_south' : 0.8,
    'refl_east' : 0.8,
    'refl_west' : 0.8,
    'refl_ceiling' : 0.8,
    'refl_floor' : 0.3,
    'm_sensor' : 1,
    'r_sensor' : np.array([2.5, 2.5, 0]),
    'm_master' : 1,
    'r_master' : np.array([5, 5, 4]),
    'FOV_master' : np.pi / 2.0,
    'FOV_sensor' : np.pi / 2.0,
    'amb_L1' : 2.0,
    'amb_L2' : 2.0,
    'nR_sensor' : constants.ez,
    'nS_sensor' : constants.ez,
    'nR_master' : -constants.ez,
    'nS_master' : -constants.ez,
    'no_bounces' : 4,
    'Rb_master' : 10e3,
    'Rb_sensor' : 10e3,  
    'PT_sensor' : 25e-3,
    'PT_master' : 6,
    'A_master' : 1e-4,
    'A_sensor' : 1e-4
   }
}
  